### ISSUE TITLE
[:install, :reconfugre] is not idempotent

### ISSUE THREAD

**Issue by vinyar** [chef-cookbooks/chef-server-ingredient#14]
Example below will skip the install, because package resource is idempotent, however, it will still bounce the server due to reconfigure. Which is unnecessary, especially if the recipe runs on cron job.

Not idempotent
```ruby
chef_server_ingredient 'chef-server-core' do
  version '12.0.8-1'
  action [:install, :reconfigure]
end
```

Idempotent*:
```ruby
chef_server_ingredient 'chef-server-core' do
  version '12.0.8-1'
  action :install
  notifies :reconfigure, 'chef_server_ingredient[reconfigure chef-server-core]', :immediately
end

chef_server_ingredient 'reconfigure chef-server-core' do
  package_name 'chef-server-core'
  action :nothing
end
```

*Note:
I have not done in-depth testing, so I am not 100% confident that LWRP will not fire off a notification if internal resources made no changes

**Comment by dblessing** [comment]
@vinyar Combine into one resource and notify self:

chef_server_ingredient 'chef-server-core' do
  version '12.0.8-1'
  action :install
  notifies :reconfigure, 'chef_server_ingredient[chef-server-core]', :immediately
end

**Comment by vinyar** [comment]
@dblessing That works fine, unless there are additional notifications. Which would cause the notification to self to run all of the additional notifications. Easy to get trapped in an endless loop that way

**Comment by dblessing** [comment]
Good point!

**Comment by smith** [comment]
Since reconfigure just does a chef-client run with the internal omnibus cookbook, is that not idempotent itself? Reconfigure shouldn't bounce the server unless something has changed telling it that it needs to happen.

**Comment by jtimberman** [comment]
Having a resource notify itself immediately can cause an infinite loop. 

Reconfigure is idempotent - but not convergent. 

For more detail on idempotent vs convergent http://stackoverflow.com/questions/30615588/difference-between-convergence-and-idempotency-in-chef :).
