### ISSUE TITLE
chef-server-ingredients should support start / stop / restart

### ISSUE THREAD

**Issue by vinyar** [chef-cookbooks/chef-server-ingredient#16]
For example, installing analytics requires restarting chef-server-core. So the cookbook has to use execute resource to bounce the services. It would be much nicer if you could just send a :restart notification to the resource.

**Comment by vinyar** [comment]
I can hack up a pull request assuming that's the direction you agree with

**Comment by johnbellone** [comment]
:+1:

**Comment by jtimberman** [comment]
This cookbook is deprecated in favor of [chef-ingredient](https://github.com/chef-cookbooks/chef-ingredient) - which has a resource, `omnibus_service`, used like this:

```ruby
omnibus_service 'chef-server/rabbitmq' do
  action :nothing
end

template '/etc/opscode/chef-server.rb' do
  # ..
  notifies :restart, 'omnibus_service[chef-server/rabbitmq]'
end
```
